### ISSUE TITLE
Change mobile breakpoints?

### ISSUE THREAD

**Issue by mrb** [fomantic/Fomantic-UI-SASS#10]
Seems like the `767.98` values are hard-coded for breakpoints (e.g. https://github.com/fomantic/Fomantic-UI-SASS/blob/master/app/assets/stylesheets/semantic-ui/collections/_grid.scss#L174) -- anyone know an easy way to tweak this?

**Comment by shanecav84** [comment]
You might need to override the media query:

```scss
@media only screen and (max-width: 767.98px) {
  .ui.page.grid {
    width: default;
    padding-left: default;
    padding-right: default;
    margin-left: default;
    margin-right: default;
  }
}
```
